name: DevSecOps Log Scan

on: [push]

jobs:
  scan-log:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run log scan with secret
        env:
          ALERT_KEY: ${{ secrets.ALERT_KEY }}
        run: |
          echo "Using secret (hidden in logs)"
          python3 check_log.py
