name: DevSecOps Log Scan

on:
  push:
    branches: [ "main" ]

jobs:
  log-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Prepare log file
      run: |
        mkdir -p logs
        echo "INFO App started" > logs/app.log

    - name: Run log scan
      run: |
        python3 check_log.py
